server:
  port: 8082
dubbo:
  consumer:
    check: false
  application:
    name: server-consumer
  protocol:
    port: 20880
    name: dubbo
  registry:
    address: 192.168.0.149:2181
    protocol: zookeeper
  scan:
    base-packages: com.cg.service
